apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: containerlog
  labels:
    strimzi.io/cluster: "my-cluster"
spec:
  partitions: 12
  replicas: 2
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: auditlog
  labels:
    strimzi.io/cluster: "my-cluster"
spec:
  partitions: 12
  replicas: 2
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
